version: "3.9"

services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"        
    networks:
      - anon-network
    depends_on:
      - backend

  backend:
    build: ./server        
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/anonboard?schema=public"
    networks:
      - anon-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: anonboard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - anon-network

volumes:
  pgdata:

networks:
  anon-network:
    driver: bridge
