name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

     
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install client dependencies
        run: |
          cd Client
          npm install
      - name: Build client
        run: |
          cd Client
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm install
      - name: Build server
        run: |
          cd server
          npm run build
